on:
  rss:
    url:
      - https://www.pcgames.de/feed.cfm?menu_alias=home/
      - https://www.giga.de/rss/giga.rss
    config:
      limit: 20
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Notify
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          webhookUrl: ${{secrets.DISCORD_WEBHOOK2}}
          content: '**${{on.rss.outputs.title}}**'
          embeds:
             color: 13107455
             description: '${{on.rss.outputs.content}} ... [Read more..](<${{on.rss.outputs.link}}>)'
             url: '<${{on.rss.outputs.link}}>'
             footer:
               text: '- Posted: ${{on.rss.outputs.pubDate}}'
          components:
          - type: 1
            components:
            - type: 2
              style: 5
              label: 'Read more..'
              url: '<${{on.rss.outputs.link}}>'


