on:
  rss:
    url:
      - https://www.pcgames.de/feed.cfm?menu_alias=home/
      - https://www.buffed.de/feed.cfm?menu_alias=home/
    config:
      limit: 20
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: discord-action
        uses: sebastianpopp/discord-action@v1.0
        with:
          event: notice
          webhook: ${{secrets.DISCORD_WEBHOOK2}}
          embed: TESTNACHRICHT
          message: |          
            ** ${{on.rss.outputs.title}} **
            
            ${{on.rss.outputs.content}} <[${{on.rss.outputs.link}}](Weiterlesen)>
            
            - Posted: ${{on.rss.outputs.pubDate}}
            - Quelle: <${{on.rss.outputs.link}}>
             
              
              
            
            





