name: Deploy
on: push
twitter:
  api: statuses/user_timeline
  auth:
   consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
   consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
   access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
   access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
  params:
    screen_name: playnewworldde
jobs:
  deploy:
   name: Deploy
   runs-on: ubuntu-latest
   steps:
   - name: discord-action
     uses: sebastianpopp/discord-action@releases/v1
     with:
      webhook: ${{ secrets.DISCORD_WEBHOOK }}
      message: Hallo @New World Gamer, hier sind Neuigkeiten ffür dich\n ${{ on.twitter.outputs.full_text }}
   run: |
