on:
 twitter:
  api: statuses/user_timeline
  auth:
   consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
   consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
   access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
   access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
  params:
    screen_name: pcg_de
    exclude_replies: true,
    include_rts: false,
    tweet_mode: extended,
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: discord-action
        uses: sebastianpopp/discord-action@v1.0
        with:
          event: notice
          webhook: ${{secrets.DISCORD_WEBHOOK2}}
          message: |
            Moin <@everyone> , gibt wieder neue GameNews für dich!
            
            ${{on.twitter.outputs.full_text}}
            
            - Quelle: http://twitter.com/${{on.twitter.outputs.user.screen_name}}
